### PR TITLE
Add username HareerSakhi

### PR DESCRIPTION
**Pull request by AvidCoder101**
This will add my username onto the _post folder.

### CODE REVIEW

**Comment by nlok5923** [comment]
please add meaningful pr description.

**Comment by HareerSakhi** [comment]
I have tried to fix it

**Comment by HareerSakhi** [comment]
I have tried to fix it

**Comment by nlok5923** [comment]
Still not meaningful the description should say what change does this pr brings to codebase.

**Comment by HareerSakhi** [comment]
I have fixed the description

**Comment by nlok5923** [comment]
> I have completed my first public repository contribution. 
the above prefix should not expected to be in your pr description please correct it.

**Comment by HareerSakhi** [comment]
I have removed this

**Review by nlok5923 — APPROVED** [review]
LGTM!!

**Pull request merged**
