### PR TITLE
Add webintellectual

### PR DESCRIPTION
**Pull request by webintellectual**
Add webintellectual.txt file containing my name, username and what I learnt

### CODE REVIEW

**Comment by nlok5923** [comment]
@webintellectual do remember if your contribution adding value to open source community "it's never too late". 

Still i can't merge 😅 this pr as the description you wrote does not states the changes you made in this repo. Sort it out and ping me once done.

**Comment by webintellectual** [comment]
Add webintellectual.txt file containing my name, username and what I learnt

**Comment by nlok5923** [comment]
> Add webintellectual.txt file containing my name, username and what I learnt

place the above text in pr description box.

**Comment by webintellectual** [comment]
ok! what I understood now is you wanted me to edit the pr description. I have done it now! 
Is it fine?

**Comment by nlok5923** [comment]
> ok! what I understood now is you wanted me to edit the pr description. I have done it now!
> Is it fine?

yup !!

**Review by nlok5923 — APPROVED** [review]
LGTM !!

**Pull request merged**
